default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: skeleton_development

test:
  <<: *default
  database: skeleton_test

production:
  <<: *default
  database: skeleton_production
  username: skeleton
  password: 
